[project]
name = "genaiserver_rg"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]

[tasks]
populate = "python genaiserver_rg/sql.py"
server = "gunicorn -w 4 -b 0.0.0.0:5000 genaiserver_rg.flask_app:app || python genaiserver_rg/flask_app.py"
devserver = "ENV=dev python -m genaiserver_rg.flask_app"

[dependencies]
flask = ">=3.0.3,<3.1"
gunicorn = ">=22.0.0,<22.1"
python-dotenv = ">=1.0.1,<1.1"
pydantic = ">=2.7.4,<2.8"
sqlalchemy = ">=2.0.30,<2.1"
click = ">=8.1.7,<8.2"
requests = ">=2.32.3,<2.33"
openai = "*"

[pypi-dependencies]
genaiserver_rg = { path = ".", editable = true }

[feature.test.dependencies]
pytest = ">=7.2.0,<7.3"
pytest-cov = ">=2.5.1,<2.6"
pytest-mock = ">=3.14.0,<3.15"

[feature.test.tasks]
test = "pytest --cov -m 'not e2e'"
test_e2e = "pytest --cov -m 'e2e'"

[feature.lintformat.dependencies]
ruff = ">=0.4.10,<0.5"
pre-commit = ">=3.1.1,<3.2"

[feature.lintformat.tasks]
lint = "ruff check"
format = "ruff format"

[feature.typing.dependencies]
mypy = ">=1.10.0,<1.11"

[feature.typing.tasks]
typing = "mypy ."

[feature.build.dependencies]
build = ">=0.7.0,<0.8"
twine = ">=3.3.0,<4.0"

[feature.build.tasks]
build = "python -m build"
publish = "python -m twine upload --repository testpypi dist/*"

[environments]

[environments.dev]
features = ["test", "lintformat", "typing"]

[environments.default]
solve-group = "default"

[environments.build]
features = ["build"]
solve-group = "default"
